Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Pre-processing

In [ ]:
# loading dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
77333,57003,-1.565835,0.537575,3.284121,3.229021,-0.917761,2.016339,-1.157749,1.086392,0.234172,...,0.125678,1.072830,-0.229837,0.094444,0.215087,0.544487,0.271867,-0.089124,25.69,0.0
77334,57005,-0.710264,-0.095320,2.899716,0.718612,-0.501955,0.968641,-0.007123,0.308006,1.383339,...,0.069589,0.711129,-0.038570,0.088990,-0.282553,-0.448201,0.054450,-0.051693,65.00,0.0
77335,57005,0.875729,-0.658494,-0.798643,-0.889801,-0.205406,-1.093946,0.743501,-0.381269,0.405087,...,0.192299,0.161282,-0.451218,0.060376,0.885705,-0.477421,-0.036297,0.035704,235.53,0.0
77336,57006,-0.679923,1.074176,1.045563,1.100620,-0.764069,-1.048969,0.601586,0.283135,-0.674820,...,0.256539,0.475028,0.124473,0.886947,-0.327076,-0.362904,0.017048,0.109040,73.52,0.0
77337,57006,1.380239,-1.328341,1.488601,-1.259442,-2.253642,-0.193980,-1.799733,0.139147,-1.245753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77338 entries, 0 to 77337
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    77338 non-null  int64
 1   V1      77338 non-null  float64
 2   V2      77338 non-null  float64
 3   V3      77338 non-null  float64
 4   V4      77338 non-null  float64
 5   V5      77338 non-null  float64
 6   V6      77338 non-null  float64
 7   V7      77338 non-null  float64
 8   V8      77338 non-null  float64
 9   V9      77338 non-null  float64
 10  V10     77338 non-null  float64
 11  V11     77338 non-null  float64
 12  V12     77338 non-null  float64
 13  V13     77338 non-null  float64
 14  V14     77337 non-null  float64
 15  V15     77337 non-null  float64
 16  V16     77337 non-null  float64
 17  V17     77337 non-null  float64
 18  V18     77337 non-null  float64
 19  V19     77337 non-null  float64
 20  V20     77337 non-null  float64
 21  V21     77337 non-null  float64
 22  V22     77337 non-null  float64
 23  V23     77337 non-null  float64
 24  V24     77337 non-null  float64
 25  V25     77337 non-null  float64
 26  V26     77337 non-null  float64
 27  V27     77337 non-null  float64
 28  V28     77337 non-null  float64
 29  Amount  77337 non-null  float64
 30  Class   77337 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 18.3 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions and fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    77149
1.0      188
Name: Class, dtype: int64

This Dataset is highly Unblanced

0--> Normal Transaction

1--> Fraudulent Transaction

In [ ]:
# seperate the data analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(77149, 31)
(188, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    77149.000000
mean        97.625867
std        270.623024
min          0.000000
25%          7.690000
50%         26.800000
75%         89.000000
max      19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     188.000000
mean       94.292500
std       214.093799
min         0.000000
25%         1.000000
50%         7.550000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,36643.938353,-0.239252,-0.043518,0.701351,0.152168,-0.264608,0.10159,-0.097359,0.046639,0.005268,...,0.042235,-0.030677,-0.105246,-0.038271,0.007363,0.134344,0.025494,0.000766,0.002836,97.625867
1.0,32055.739362,-6.692335,4.711159,-8.903156,5.250821,-4.905270,-2.04085,-7.040342,3.194879,-3.137542,...,0.374793,0.797237,-0.171993,-0.229811,-0.084322,0.242355,0.097236,0.586565,0.050794,94.292500

Under Sampling

Build a sample dataset containing similiar distribution of normal transactions and fraudulent Transactions

Number of fraudulant Transactions--> 492

In [18]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [19]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [21]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
74219,55473,1.070089,-1.942844,0.786723,-0.879527,-2.213576,-0.139357,-1.251041,0.107543,-1.121741,...,-0.132916,-0.156870,-0.160866,0.530748,0.369454,-0.134653,0.021420,0.040194,186.56,0.0
64014,50984,0.587095,-0.522091,1.202235,2.605644,-0.522567,1.411610,-0.488907,0.472863,-0.372784,...,0.348141,0.690125,-0.194130,-0.252899,0.153910,0.124152,0.030829,0.055780,217.20,0.0
50393,44473,-0.905289,0.597236,1.056740,0.660906,0.759282,0.080494,0.790452,-0.038719,-0.412046,...,0.088157,0.646377,-0.044708,-0.297580,-0.182709,-0.304248,0.371445,0.102830,62.79,0.0
17292,28606,-0.366099,0.248761,1.494387,-2.331751,-0.214947,-1.234318,0.489066,-0.227609,-1.317444,...,0.065633,0.021791,0.090277,0.381708,-0.584179,-0.912334,0.137270,0.176146,15.00,0.0
37295,38897,1.155328,-0.376956,-0.201617,-0.000238,1.380655,3.954146,-1.268713,1.080864,0.561194,...,0.220077,0.477859,-0.135287,1.015326,0.518872,-0.242822,0.073415,0.042640,40.88,0.0

In [22]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
75511,56098,-1.229669,1.956099,-0.851198,2.796987,-1.913977,-0.044934,-1.340739,-0.555548,-1.184468,...,1.208054,0.277612,0.019266,0.508529,-0.201183,-0.249600,0.562239,0.075309,170.92,1.0
76555,56624,-7.901421,2.720472,-7.885936,6.348334,-5.480119,-0.333059,-8.682376,1.164431,-4.542447,...,0.077739,1.092437,0.320133,-0.434643,-0.380687,0.213630,0.423620,-0.105169,153.46,1.0
76609,56650,-8.762083,2.791030,-7.682767,6.991214,-5.230695,-0.357388,-9.685621,1.749335,-4.495679,...,-0.090527,0.348590,0.051132,-0.415430,0.219665,0.330020,-0.028252,-0.156270,7.52,1.0
76929,56806,0.016828,2.400826,-4.220360,3.462217,-0.624142,-1.294303,-2.986028,0.751883,-1.606672,...,0.285832,-0.771508,-0.265200,-0.873077,0.939776,-0.219085,0.874494,0.470434,1.00,1.0
77099,56887,-0.075483,1.812355,-2.566981,4.127549,-1.628532,-0.805895,-3.390135,1.019353,-2.451251,...,0.794372,0.270471,-0.143624,0.013566,0.634203,0.213693,0.773625,0.387434,5.00,1.0

In [23]:
new_dataset['Class'].value_counts()

0.0    492
1.0    188
Name: Class, dtype: int64

In [25]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,37133.928862,-0.316408,-0.034825,0.743738,0.129778,-0.250608,0.08225,-0.107922,0.058953,-0.034710,...,-0.004790,-0.062363,-0.093366,-0.037541,0.002276,0.127752,0.017881,-0.023195,-0.001093,86.638821
1.0,32055.739362,-6.692335,4.711159,-8.903156,5.250821,-4.905270,-2.04085,-7.040342,3.194879,-3.137542,...,0.374793,0.797237,-0.171993,-0.229811,-0.084322,0.242355,0.097236,0.586565,0.050794,94.292500

Spliting the data into Features and Targets

In [45]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [28]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
74219  55473  1.070089 -1.942844  0.786723 -0.879527 -2.213576 -0.139357
64014  50984  0.587095 -0.522091  1.202235  2.605644 -0.522567  1.411610
50393  44473 -0.905289  0.597236  1.056740  0.660906  0.759282  0.080494
17292  28606 -0.366099  0.248761  1.494387 -2.331751 -0.214947 -1.234318
37295  38897  1.155328 -0.376956 -0.201617 -0.000238  1.380655  3.954146
...      ...       ...       ...       ...       ...       ...       ...
75511  56098 -1.229669  1.956099 -0.851198  2.796987 -1.913977 -0.044934
76555  56624 -7.901421  2.720472 -7.885936  6.348334 -5.480119 -0.333059
76609  56650 -8.762083  2.791030 -7.682767  6.991214 -5.230695 -0.357388
76929  56806  0.016828  2.400826 -4.220360  3.462217 -0.624142 -1.294303
77099  56887 -0.075483  1.812355 -2.566981  4.127549 -1.628532 -0.805895

             V7        V8        V9  ...       V20       V21       V22  \
74219 -1.251041  0.107543 -1.121741  ... -0.077556 -0.132916 -0.156870
64014 -0.488907  0.472863 -0.372784  ...  0.267168  0.348141  0.690125
50393  0.790452 -0.038719 -0.412046  ...  0.372359  0.088157  0.646377
17292  0.489066 -0.227609 -1.317444  ...  0.003846  0.065633  0.021791
37295 -1.268713  1.080864  0.561194  ...  0.089266  0.220077  0.477859
...         ...       ...       ...  ...       ...       ...       ...
75511 -1.340739 -0.555548 -1.184468  ...  0.270459  1.208054  0.277612
76555 -8.682376  1.164431 -4.542447  ... -0.614719  0.077739  1.092437
76609 -9.685621  1.749335 -4.495679  ... -0.460390 -0.090527  0.348590
76929 -2.986028  0.751883 -1.606672  ...  0.590418  0.285832 -0.771508
77099 -3.390135  1.019353 -2.451251  ...  0.338598  0.794372  0.270471

            V23       V24       V25       V26       V27       V28  Amount
74219 -0.160866  0.530748  0.369454 -0.134653  0.021420  0.040194  186.56
64014 -0.194130 -0.252899  0.153910  0.124152  0.030829  0.055780  217.20
50393 -0.044708 -0.297580 -0.182709 -0.304248  0.371445  0.102830   62.79
17292  0.090277  0.381708 -0.584179 -0.912334  0.137270  0.176146   15.00
37295 -0.135287  1.015326  0.518872 -0.242822  0.073415  0.042640   40.88
...         ...       ...       ...       ...       ...       ...     ...
75511  0.019266  0.508529 -0.201183 -0.249600  0.562239  0.075309  170.92
76555  0.320133 -0.434643 -0.380687  0.213630  0.423620 -0.105169  153.46
76609  0.051132 -0.415430  0.219665  0.330020 -0.028252 -0.156270    7.52
76929 -0.265200 -0.873077  0.939776 -0.219085  0.874494  0.470434    1.00
77099 -0.143624  0.013566  0.634203  0.213693  0.773625  0.387434    5.00

[680 rows x 30 columns]

In [29]:
print(Y)

74219    0.0
64014    0.0
50393    0.0
17292    0.0
37295    0.0
        ...
75511    1.0
76555    1.0
76609    1.0
76929    1.0
77099    1.0
Name: Class, Length: 680, dtype: float64

Split the data into Training data and testing Data

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [49]:
print(X.shape,X_train.shape, X_test.shape)

(680, 30) (544, 30) (136, 30)

Model Training

Logistic Regression

In [50]:
model = LogisticRegression()

In [57]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

Model Evaluation

Accuracy Score

In [53]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [54]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9632352941176471

In [55]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [56]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9264705882352942